In [11]:
from numpy import genfromtxt 
import keras
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation

In [12]:
#import the dataset
feature=genfromtxt('dataset.csv', delimiter=',', usecols=(i for i in range(0,215)),dtype=float,skip_header=1)
class_value=genfromtxt('dataset.csv', delimiter=',', usecols=(-1), dtype=str, skip_header=1)
print(feature)
print(class_value)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]]
['S' 'S' 'S' ... 'B' 'B' 'B']


Preprocessing Data

In [13]:
#preprocessing of data s=malware --> 1, b=begnin --> 0
from sklearn.preprocessing import LabelEncoder, StandardScaler
feature_std = StandardScaler().fit_transform(feature)
class_value = LabelEncoder().fit_transform(class_value)  
print(class_value)

[1 1 1 ... 0 0 0]


In [14]:
# split data
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(feature, class_value,test_size=0.25, random_state=1)
print(x_train.shape)
print(y_train.shape)

(11277, 215)
(11277,)


In [15]:
#build the model
model = Sequential ([
    Dense(32, input_shape=(215,), activation='relu'),
    Dense(1, activation='sigmoid'),
])

In [16]:
#compile our model
from tensorflow.keras.metrics import categorical_crossentropy
from tensorflow.keras.optimizers import Adam

model.compile(Adam(lr=.001), loss='binary_crossentropy', metrics=['accuracy'])

In [17]:
# train the model
model.fit(x_train, y_train, batch_size=10, epochs=50, shuffle=True, verbose=2)

Epoch 1/50
1128/1128 - 1s - loss: nan - accuracy: 0.8148
Epoch 2/50
1128/1128 - 1s - loss: nan - accuracy: 0.6313
Epoch 3/50
1128/1128 - 1s - loss: nan - accuracy: 0.6313
Epoch 4/50
1128/1128 - 1s - loss: nan - accuracy: 0.6313
Epoch 5/50
1128/1128 - 1s - loss: nan - accuracy: 0.6313
Epoch 6/50
1128/1128 - 1s - loss: nan - accuracy: 0.6313
Epoch 7/50
1128/1128 - 1s - loss: nan - accuracy: 0.6313
Epoch 8/50
1128/1128 - 1s - loss: nan - accuracy: 0.6313
Epoch 9/50
1128/1128 - 1s - loss: nan - accuracy: 0.6313
Epoch 10/50
1128/1128 - 1s - loss: nan - accuracy: 0.6313
Epoch 11/50


KeyboardInterrupt: 

In [ ]:
#evaluate the model