In [1]:
import numpy as np
from numpy import genfromtxt 
import keras
from keras.utils import np_utils
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation, Input

In [2]:
#import the dataset
feature=genfromtxt('dataset.csv', delimiter=',', usecols=(i for i in range(0,215)),dtype=float,skip_header=1)
class_value=genfromtxt('dataset.csv', delimiter=',', usecols=(-1), dtype=str, skip_header=1)
print(feature)
print(class_value)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]]
['S' 'S' 'S' ... 'B' 'B' 'B']


Preprocessing Data

In [3]:
#preprocessing of data s=malware --> 1, b=begnin --> 0
from sklearn.preprocessing import LabelEncoder, StandardScaler
#feature_std = StandardScaler().fit_transform(feature)
class_value = LabelEncoder().fit_transform(class_value)  
print(class_value)

[1 1 1 ... 0 0 0]


In [14]:
class_value_cat = np_utils.to_categorical(class_value, num_classes=2)
print(class_value_cat)

[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]


In [18]:
# split data
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(feature, class_value_cat,test_size=0.25, random_state=1)
print(x_train.shape)
print(y_train.shape)

(11277, 215)
(11277, 2)


In [19]:
x_train=np.array(x_train)
x_test=np.array(x_test)
y_train=np.array(y_train)
y_test=np.array(y_test)

In [20]:
print(x_train[1].shape)
print(y_train[1].shape)

(215,)
(2,)


In [21]:
# number of features = x_train.shape[1]
print(x_train.shape[1])
# number of classes 

215


In [26]:
#build the model
model = Sequential ([
    Input(shape=(x_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(16, activation='relu'),
    #sigmoid is a logistic regression function, softmax transform a vector into a vector of probabilities
    Dense(2, activation='softmax')  
])
model.summary()
print(model.output_shape)
print(model.compute_output_signature)

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 32)                6912      
_________________________________________________________________
dense_7 (Dense)              (None, 16)                528       
_________________________________________________________________
dense_8 (Dense)              (None, 2)                 34        
Total params: 7,474
Trainable params: 7,474
Non-trainable params: 0
_________________________________________________________________
(None, 2)
<bound method Layer.compute_output_signature of <tensorflow.python.keras.engine.sequential.Sequential object at 0x000001A7BB821550>>


In [27]:
sgd = keras.optimizers.SGD(lr=0.001, decay=1e-6, momentum=0.9, nesterov=True)

In [28]:
#compile our model
from tensorflow.keras.metrics import categorical_crossentropy
from tensorflow.keras.optimizers import Adam

#model.compile(Adam(lr=.001), loss='categorical_crossentropy', metrics=['accuracy'])
#model.compile(optimizer=sgd, loss='mean_squared_error', metrics=['accuracy'])
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [29]:
# train the model
model.fit(x=x_train, y=y_train, batch_size=10, epochs=10, shuffle=True, validation_data=(x_test, y_test))


Epoch 1/10
1128/1128 [==============================] - 2s 2ms/step - loss: nan - accuracy: 0.7512 - val_loss: nan - val_accuracy: 0.6270
Epoch 2/10
1128/1128 [==============================] - 2s 2ms/step - loss: nan - accuracy: 0.6313 - val_loss: nan - val_accuracy: 0.6270
Epoch 3/10
1128/1128 [==============================] - 2s 2ms/step - loss: nan - accuracy: 0.6313 - val_loss: nan - val_accuracy: 0.6270
Epoch 4/10
1128/1128 [==============================] - 2s 2ms/step - loss: nan - accuracy: 0.6313 - val_loss: nan - val_accuracy: 0.6270
Epoch 5/10
1128/1128 [==============================] - 2s 2ms/step - loss: nan - accuracy: 0.6313 - val_loss: nan - val_accuracy: 0.6270
Epoch 6/10
   1/1128 [..............................] - ETA: 0s - loss: nan - accuracy: 0.8000

KeyboardInterrupt: 